name: DANE_Failed_Actions_Resolver
on:
  workflow_run:
    workflows:
      - 'Socket Security: Project Report'
    types:
      - completed

jobs:
  analyze_failed_action:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dane cli
        run: pnpm install -g @mastra/dane@alpha

      - name: Get PR number
        id: get-pr
        run: |
          PR_NUMBER=$(gh api /repos/${{ github.repository }}/pulls \
            --jq ".[] | select(.head.sha == '${{ github.event.workflow_run.head_sha }}') | .number")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Analyze Actions
        if: steps.get-pr.outputs.PR_NUMBER != ''
        run: dane action-resolver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
          PULL_NUMBER: ${{ steps.get-pr.outputs.PR_NUMBER }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
