name: DANE_Failed_Actions_Resolver
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      pull_number:
        description: 'Pull Request Number'
        required: true
        type: string

jobs:
  analyze_failed_action:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dane cli
        run: pnpm install -g @mastra/dane@alpha

      - name: Analyze Actions
        run: dane action-resolver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
          PULL_NUMBER: ${{ github.event.pull_request.number || inputs.pull_number }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
