name: Delete Spam Issues

on:
  issues:
    types: [labeled]

jobs:
  delete-spam:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'spam'
    permissions:
      issues: write
    
    steps:
      - name: Delete spam issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.delete({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
